"use node";

import { v } from "convex/values";
import { action } from "./_generated/server";
import type { ActionCtx } from "./_generated/server";
import { modelComplete } from "./lib/modelGateway";
import type { Id } from "./_generated/dataModel";
import {
  actionProjectSnapshot,
  consumeAiQuotaForAction,
  requireActionUser,
  type ProjectSnapshot,
} from "./guards";

// The snapshot type lives with the loader (T0.4); re-exported so existing
// consumers keep one import site.
export type { ProjectSnapshot };

/* ── Shared helpers ───────────────────────────────────────────────────── */

async function complete(
  ctx: ActionCtx,
  userId: Id<"users">,
  projectId: Id<"projects">,
  agentId: string,
  system: string,
  messages: Array<{ role: "user" | "assistant"; content: string }>,
  opts: { temperature?: number; maxTokens?: number; validateOutput?: (text: string) => void } = {},
): Promise<string> {
  const result = await modelComplete({
    ctx,
    userId,
    projectId,
    agentId,
    promptVersion: "v1",
    autonomy: "assistive",
    contextSources: ["project.snapshot", "request.context"],
    model: "gpt-4o-mini",
    messages: [{ role: "system", content: system }, ...messages],
    temperature: opts.temperature ?? 0.7,
    maxOutputTokens: opts.maxTokens ?? 900,
    validateOutput: opts.validateOutput,
  });
  return result.text;
}

/** The AI prompt's business context is built SERVER-side from the database
 *  (project row + attached-file excerpts + active products) by
 *  `guards.actionProjectSnapshot`, after the caller's access to the project
 *  is verified. The client passes only a `projectId` it owns — never a
 *  snapshot (pack T0.4; AGENTS.md §5 rule 3: client input is untrusted). */

function contextLines(p: ProjectSnapshot): string[] {
  return [
    `Project: ${p.name}`,
    p.industry ? `Industry: ${p.industry}` : "",
    p.description ? `Description: ${p.description}` : "",
    p.websiteUrl ? `Website: ${p.websiteUrl}` : "",
    p.productsServices?.length
      ? `Products/services: ${p.productsServices.join(", ")}`
      : "",
    p.goals?.length ? `Marketing goals: ${p.goals.join(", ")}` : "",
    p.competitors?.length ? `Competitors: ${p.competitors.join(", ")}` : "",
    p.gmbTitle
      ? `Google Business: ${p.gmbTitle}${p.gmbCategory ? ` (${p.gmbCategory})` : ""}${p.gmbRating ? ` — ${p.gmbRating}★ from ${p.gmbReviews ?? "?"} reviews` : ""}`
      : "",
    p.fileExcerpts?.length
      ? `Attached files (excerpts):\n${p.fileExcerpts.join("\n")}`
      : "",
    p.products?.length
      ? `Catalog (canonical products):\n${p.products
          .map(
            (pr) =>
              `- ${pr.title}${pr.price ? ` — ${pr.price}` : ""}${pr.description ? `: ${pr.description.slice(0, 120)}` : ""}`,
          )
          .join("\n")}`
      : "",
  ].filter(Boolean);
}

const PERSONA_JSON_SHAPE = `Return ONLY valid JSON (no markdown fences) shaped as:
{
  "name": string,
  "role": string,
  "goals": string[],
  "pains": string[],
  "objections": string[],
  "channels": string[],
  "evidence": string
}`;

function parsePersona(json: string) {
  const cleaned = json.replace(/```json|```/g, "").trim();
  const start = cleaned.indexOf("{");
  const end = cleaned.lastIndexOf("}");
  if (start === -1 || end === -1) throw new Error("AI returned unparseable persona");
  const raw = JSON.parse(cleaned.slice(start, end + 1)) as {
    name?: string;
    role?: string;
    goals?: unknown;
    pains?: unknown;
    objections?: unknown;
    channels?: unknown;
    evidence?: string;
  };
  const arr = (x: unknown): string[] =>
    Array.isArray(x) ? x.filter((i): i is string => typeof i === "string").slice(0, 8) : [];
  return {
    name: raw.name?.trim() || "Persona",
    role: raw.role?.trim() || undefined,
    goals: arr(raw.goals),
    pains: arr(raw.pains),
    objections: arr(raw.objections),
    channels: arr(raw.channels),
    evidence: raw.evidence?.trim() || "Generated by AI from project context",
  };
}

function parseStructuredObject(text: string): Record<string, unknown> {
  const cleaned = text.replace(/```json|```/g, "").trim();
  const start = cleaned.indexOf("{");
  const end = cleaned.lastIndexOf("}");
  if (start === -1 || end === -1) throw new Error("invalid structured output");
  const value: unknown = JSON.parse(cleaned.slice(start, end + 1));
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("invalid structured output");
  return value as Record<string, unknown>;
}

export function validateJourneyMapOutput(text: string): void {
  const value = parseStructuredObject(text);
  if (
    !Array.isArray(value.stages) ||
    !value.stages.length ||
    value.stages.some(
      (stage) =>
        !stage ||
        typeof stage !== "object" ||
        typeof (stage as { stage?: unknown }).stage !== "string",
    )
  ) {
    throw new Error("invalid journey");
  }
}

/* ── Create-module actions: gaps → topics → writing ───────────────────── */

/**
 * Detect content gaps per persona × journey stage from project context,
 * personas and journey maps. Returns structured gaps; caller persists via
 * contentPlanning.createGap.
 */
export const detectContentGaps = action({
  args: {
    projectId: v.id("projects"),
    personas: v.array(
      v.object({
        id: v.string(),
        name: v.string(),
        role: v.optional(v.string()),
        goals: v.optional(v.array(v.string())),
        pains: v.optional(v.array(v.string())),
        objections: v.optional(v.array(v.string())),
      }),
    ),
    journeys: v.array(
      v.object({
        id: v.string(),
        personaId: v.optional(v.string()),
        name: v.string(),
        goal: v.optional(v.string()),
        stages: v.array(
          v.object({
            stage: v.string(),
            score: v.optional(v.number()),
            pains: v.optional(v.string()),
            opportunities: v.optional(v.string()),
          }),
        ),
      }),
    ),
  },
  handler: async (ctx, { projectId, personas, journeys }) => {
    const userId = await requireActionUser(ctx);
    const project = await actionProjectSnapshot(ctx, userId, projectId);
    await consumeAiQuotaForAction(ctx, userId);
    const text = await complete(ctx, userId, projectId, "create.content_gaps",
      `You are a content strategist auditing a business's content coverage. Identify CONTENT GAPS: questions, topics or moments in the customer journey where the business has no good content answering the persona's real need. Ground every gap in the persona's pains/goals and the journey stage (weakest stages = biggest gaps). Return ONLY valid JSON (no markdown) shaped as:
{"gaps": [{"personaId": string|null, "journeyMapId": string|null, "journeyStage": string|null, "title": string, "description": string, "severity": "low"|"medium"|"high"}]}
Give 5-10 gaps. Use the provided persona/journey ids exactly. title = short label (≤8 words). description = 1-2 sentences on what's missing and why it matters.`,
      [
        {
          role: "user",
          content: `${contextLines(project).join("\n")}\n\nPersonas:\n${personas.map((p) => `- [${p.id}] ${p.name}${p.role ? ` (${p.role})` : ""}${p.pains?.length ? ` — pains: ${p.pains.join("; ")}` : ""}`).join("\n") || "(none)"}\n\nJourney maps:\n${journeys.map((j) => `- [${j.id}] ${j.name}${j.personaId ? ` (persona ${j.personaId})` : ""}\n${j.stages.map((s) => `    • ${s.stage}${typeof s.score === "number" ? ` (score ${s.score}/10)` : ""}${s.pains ? ` — pains: ${s.pains}` : ""}`).join("\n")}`).join("\n") || "(none)"}`,
        },
      ],
      { temperature: 0.6, maxTokens: 1400, validateOutput: (output) => {
        const value = parseStructuredObject(output);
        if (!Array.isArray(value.gaps) || !value.gaps.some((gap) => gap && typeof gap === "object" && typeof (gap as { title?: unknown }).title === "string" && (gap as { title: string }).title.trim())) throw new Error("invalid gaps");
      } },
    );

    const cleaned = text.replace(/```json|```/g, "").trim();
    const start = cleaned.indexOf("{");
    const end = cleaned.lastIndexOf("}");
    if (start === -1 || end === -1) throw new Error("AI returned an unreadable response");
    const raw = JSON.parse(cleaned.slice(start, end + 1)) as {
      gaps?: Array<{
        personaId?: string | null;
        journeyMapId?: string | null;
        journeyStage?: string | null;
        title?: string;
        description?: string;
        severity?: string;
      }>;
    };
    const validIds = new Set([...personas.map((p) => p.id), ...journeys.map((j) => j.id)]);
    const gaps = (raw.gaps ?? [])
      .filter(
        (g): g is NonNullable<typeof g> & { title: string } =>
          typeof g?.title === "string" && g.title.trim() !== "",
      )
      .slice(0, 12)
      .map((g) => ({
        personaId:
          typeof g.personaId === "string" && validIds.has(g.personaId)
            ? (g.personaId as Id<"personas">)
            : undefined,
        journeyMapId:
          typeof g.journeyMapId === "string" && validIds.has(g.journeyMapId)
            ? (g.journeyMapId as Id<"journeyMaps">)
            : undefined,
        journeyStage:
          typeof g.journeyStage === "string" && g.journeyStage.trim() !== ""
            ? g.journeyStage.trim()
            : undefined,
        title: g.title.trim().slice(0, 120),
        description: typeof g.description === "string" ? g.description.trim() : undefined,
        severity:
          g.severity === "low" || g.severity === "medium" || g.severity === "high"
            ? g.severity
            : ("medium" as const),
      }));
    if (!gaps.length) throw new Error("AI returned no gaps");
    return { gaps };
  },
});

/**
 * Suggest topics (with angle + best content type + keywords) to fill a gap.
 * Caller persists via contentPlanning.createTopic.
 */
export const suggestTopics = action({
  args: {
    projectId: v.id("projects"),
    gap: v.object({
      title: v.string(),
      description: v.optional(v.string()),
      personaName: v.optional(v.string()),
      journeyStage: v.optional(v.string()),
    }),
    researchDigest: v.optional(v.array(v.string())), // condensed research hits
  },
  handler: async (ctx, { projectId, gap, researchDigest }) => {
    const userId = await requireActionUser(ctx);
    const project = await actionProjectSnapshot(ctx, userId, projectId);
    await consumeAiQuotaForAction(ctx, userId);
    const text = await complete(ctx, userId, projectId, "create.topic_suggestions",
      `You are a content strategist. For the given content gap, propose 4 concrete, distinct topics to fill it. For each: title (audience-facing, specific), angle (the hook that makes it fresh), contentType — one of landing_page|script|social_post|social_series|blog|email|video_script — and 2-4 keywords. Return ONLY valid JSON shaped as:
{"topics": [{"title": string, "angle": string, "contentType": string, "keywords": string[]}]}`,
      [
        {
          role: "user",
          content: `${contextLines(project).join("\n")}\n\nGap to fill: ${gap.title}\n${gap.description ?? ""}\n${gap.personaName ? `Audience persona: ${gap.personaName}` : ""}\n${gap.journeyStage ? `Journey stage: ${gap.journeyStage}` : ""}\n\nLive research findings:\n${(researchDigest ?? []).slice(0, 20).join("\n") || "(none)"}`,
        },
      ],
      { temperature: 0.8, maxTokens: 900, validateOutput: (output) => {
        const value = parseStructuredObject(output);
        if (!Array.isArray(value.topics) || !value.topics.some((topic) => topic && typeof topic === "object" && typeof (topic as { title?: unknown }).title === "string" && (topic as { title: string }).title.trim())) throw new Error("invalid topics");
      } },
    );

    const cleaned = text.replace(/```json|```/g, "").trim();
    const start = cleaned.indexOf("{");
    const end = cleaned.lastIndexOf("}");
    if (start === -1 || end === -1) throw new Error("AI returned an unreadable response");
    const raw = JSON.parse(cleaned.slice(start, end + 1)) as {
      topics?: Array<{ title?: string; angle?: string; contentType?: string; keywords?: unknown }>;
    };
    const CONTENT_TYPES = [
      "landing_page", "script", "social_post", "social_series",
      "blog", "email", "video_script",
    ];
    const topics = (raw.topics ?? [])
      .filter(
        (t): t is NonNullable<typeof t> & { title: string } =>
          typeof t?.title === "string" && t.title.trim() !== "",
      )
      .slice(0, 6)
      .map((t) => ({
        title: t.title.trim().slice(0, 160),
        angle: typeof t.angle === "string" ? t.angle.trim() : undefined,
        contentType:
          typeof t.contentType === "string" && CONTENT_TYPES.includes(t.contentType)
            ? t.contentType
            : "blog",
        keywords: Array.isArray(t.keywords)
          ? t.keywords.filter((k): k is string => typeof k === "string").slice(0, 4)
          : [],
      }));
    if (!topics.length) throw new Error("AI returned no topics");
    return { topics };
  },
});

/**
 * Generate the full content piece (HTML for Tiptap) from the topic,
 * persona, journey context and research findings. Type-aware.
 */
export const generateContent = action({
  args: {
    projectId: v.id("projects"),
    topic: v.object({
      title: v.string(),
      angle: v.optional(v.string()),
      contentType: v.optional(v.string()),
      keywords: v.optional(v.array(v.string())),
    }),
    persona: v.optional(
      v.object({
        name: v.string(),
        role: v.optional(v.string()),
        goals: v.optional(v.array(v.string())),
        pains: v.optional(v.array(v.string())),
        objections: v.optional(v.array(v.string())),
      }),
    ),
    journeyStage: v.optional(v.string()),
    researchDigest: v.optional(v.array(v.string())),
    userInstructions: v.optional(v.string()),
  },
  handler: async (ctx, { projectId, topic, persona, journeyStage, researchDigest, userInstructions }) => {
    const userId = await requireActionUser(ctx);
    const project = await actionProjectSnapshot(ctx, userId, projectId);
    await consumeAiQuotaForAction(ctx, userId);
    const TYPE_GUIDE: Record<string, string> = {
      landing_page:
        "a high-converting landing page: hero headline + subhead, 3 benefit sections each with heading + 2-3 sentences, a social-proof section, and a clear CTA section",
      blog:
        "a blog article: engaging intro, 4-6 H2 sections each with 2-4 substantial paragraphs, a conclusion with a takeaway, useful where natural a bullet list",
      social_post:
        "a single social media post: 80-150 words, hook first line, short paragraphs/line breaks, 1-3 relevant hashtags at the end",
      social_series:
        "a social media series of 4-5 posts: each post as an H2 heading (Post 1: …) followed by its short post copy",
      script:
        "a script: H2 scene/section headings with spoken lines as paragraphs, [bracketed] stage directions where helpful",
      video_script:
        "a video script: H2 section headings (Hook, Main points, CTA) with spoken lines as paragraphs and [b-roll/cut] notes in brackets",
      email:
        "an email: subject line as H2, preview text, short scannable body with one clear CTA",
    };
    const contentType = topic.contentType ?? "blog";
    const personaDesc = persona
      ? `\nWrite for persona: ${persona.name}${persona.role ? ` (${persona.role})` : ""}${persona.pains?.length ? ` — pains: ${persona.pains.join("; ")}` : ""}${persona.objections?.length ? ` — objections to handle: ${persona.objections.join("; ")}` : ""}`
      : "";

    const text = await complete(ctx, userId, projectId, "create.content_generation",
      `You are an expert content writer. Write the full content piece as clean HTML using only <h1>, <h2>, <p>, <ul>, <ol>, <li>, <strong>, <em> tags. Start with an <h1>. Format: ${TYPE_GUIDE[contentType] ?? TYPE_GUIDE.blog}. Match the brand voice of the business and speak the persona's language. Ground claims in the research findings where given. Return ONLY the HTML, no markdown fences, no explanation.${personaDesc}${journeyStage ? `\nThis content targets the journey stage: ${journeyStage}.` : ""}`,
      [
        {
          role: "user",
          content: `${contextLines(project).join("\n")}\n\nTopic: ${topic.title}\n${topic.angle ? `Angle: ${topic.angle}` : ""}\n${topic.keywords?.length ? `Keywords to include naturally: ${topic.keywords.join(", ")}` : ""}\n\nResearch findings to ground it:\n${(researchDigest ?? []).slice(0, 25).join("\n") || "(none)"}\n${userInstructions ? `\nUser instructions: ${userInstructions}` : ""}`,
        },
      ],
      { temperature: 0.7, maxTokens: 2400 },
    );

    // strip anything outside a bare HTML doc
    const html = text
      .replace(/```html|```/g, "")
      .replace(/^[\s\S]*?<body>/i, "")
      .replace(/<\/body>[\s\S]*$/i, "")
      .trim();
    if (!html) throw new Error("AI returned empty content");
    return html;
  },
});

/**
 * AI-edit a selection inside Tiptap: expand or rewrite (or custom ops later).
 * Returns HTML for the replacement fragment.
 */
export const editSelection = action({
  args: {
    op: v.union(v.literal("expand"), v.literal("rewrite")),
    selectionHtml: v.string(),
    surroundingContext: v.optional(v.string()),
    projectId: v.id("projects"),
    personaName: v.optional(v.string()),
    instruction: v.optional(v.string()),
  },
  handler: async (ctx, { op, selectionHtml, surroundingContext, projectId, personaName }) => {
    const userId = await requireActionUser(ctx);
    const project = await actionProjectSnapshot(ctx, userId, projectId);
    await consumeAiQuotaForAction(ctx, userId);
    const text = await complete(ctx, userId, projectId, "create.selection_edit",
      op === "expand"
        ? `You are an expert content editor. The user selected part of a document. Expand the selection: keep its meaning, language and voice, add depth/examples/nuance so it is roughly 2-3x longer. Return ONLY the replacement HTML using only <p>, <ul>, <ol>, <li>, <strong>, <em> tags. No preamble.${personaName ? ` Audience: ${personaName}.` : ""}`
        : `You are an expert content editor. The user selected part of a document. Rewrite the selection: same core meaning, fresh wording and structure, matching the document's voice. Return ONLY the replacement HTML using only <p>, <ul>, <ol>, <li>, <strong>, <em> tags. No preamble.${personaName ? ` Audience: ${personaName}.` : ""}`,
      [
        {
          role: "user",
          content: `${contextLines(project).join("\n")}\n\nDocument context around the selection:\n${(surroundingContext ?? "(start of document)").slice(-1500)}\n\nSelected text:\n${selectionHtml}`,
        },
      ],
      { temperature: op === "expand" ? 0.8 : 0.6, maxTokens: 1200 },
    );
    const html = text.replace(/```html|```/g, "").trim();
    if (!html) throw new Error("AI returned empty content");
    return html;
  },
});

/* ── Actions ─────────────────────────────────────────────────────────── */

/**
 * Generate a full persona from project details (files included) using AI.
 * The client passes a project snapshot (already fetched via projects.get);
 * the returned persona is persisted by the caller via personas.create.
 */
export const generatePersona = action({
  args: { projectId: v.id("projects"), hint: v.optional(v.string()) },
  handler: async (ctx, { projectId, hint }) => {
    const userId = await requireActionUser(ctx);
    const project = await actionProjectSnapshot(ctx, userId, projectId);
    await consumeAiQuotaForAction(ctx, userId);
    const text = await complete(ctx, userId, projectId, "understand.persona_generation",
      `You are a senior marketing strategist. Given the business context below, invent ONE realistic, specific buyer persona. Be concrete (names, habits, real-world details) and ground every trait in the business context. ${PERSONA_JSON_SHAPE}`,
      [
        {
          role: "user",
          content: `${contextLines(project).join("\n")}\n${hint ? `Extra guidance from the user: ${hint}` : ""}`,
        },
      ],
      { temperature: 0.8, maxTokens: 700, validateOutput: (output) => { parsePersona(output); } },
    );

    return parsePersona(text);
  },
});

/**
 * Chat with a persona (mode=persona — you talk to the buyer) or with an AI
 * marketing analyst about the persona (mode=analyst). Pure AI call — the
 * client passes the persona snapshot and prior thread, and persists the
 * exchange via personaChat.append.
 */
export const personaChat = action({
  args: {
    mode: v.union(v.literal("persona"), v.literal("analyst")),
    projectId: v.id("projects"),
    persona: v.object({
      name: v.string(),
      role: v.optional(v.string()),
      goals: v.optional(v.array(v.string())),
      pains: v.optional(v.array(v.string())),
      objections: v.optional(v.array(v.string())),
      channels: v.optional(v.array(v.string())),
      evidence: v.optional(v.string()),
    }),
    history: v.optional(
      v.array(
        v.object({
          role: v.union(v.literal("user"), v.literal("assistant")),
          content: v.string(),
        }),
      ),
    ),
    message: v.string(),
  },
  handler: async (ctx, { mode, projectId, persona, history, message }) => {
    const userId = await requireActionUser(ctx);
    const project = await actionProjectSnapshot(ctx, userId, projectId);
    await consumeAiQuotaForAction(ctx, userId);
    const personaDesc = [
      `Persona name: ${persona.name}`,
      persona.role ? `Role/context: ${persona.role}` : "",
      persona.goals?.length ? `Goals: ${persona.goals.join("; ")}` : "",
      persona.pains?.length ? `Pains: ${persona.pains.join("; ")}` : "",
      persona.objections?.length ? `Objections: ${persona.objections.join("; ")}` : "",
      persona.channels?.length ? `Channels: ${persona.channels.join(", ")}` : "",
      persona.evidence ? `Evidence: ${persona.evidence}` : "",
    ]
      .filter(Boolean)
      .join("\n");

    const ctxBlock = contextLines(project).join("\n");

    const system =
      mode === "persona"
        ? `You ARE this buyer persona. Stay in character in every answer — first person, with their vocabulary, priorities and attitude. You know nothing about marketing theory; you are a real person. If asked about products/services, react as this person realistically would based on your pains and goals.\n\nBusiness selling to you:\n${ctxBlock}\n\nYour persona definition:\n${personaDesc}`
        : `You are an experienced marketing analyst. The user will ask about the persona below and how it relates to the business's marketing (content, website, campaigns, data). Answer with sharp, specific, actionable analysis. Reference the persona's pains/goals and the business context. Use short paragraphs or bullet lists.\n\nBusiness context:\n${ctxBlock}\n\nPersona:\n${personaDesc}`;

    const reply = await complete(ctx, userId, projectId, "understand.persona_chat",
      system,
      [...(history ?? []).slice(-16), { role: "user" as const, content: message }],
      { temperature: mode === "persona" ? 0.9 : 0.5, maxTokens: 700 },
    );

    return reply;
  },
});

/**
 * Generate a full journey map (stages × lanes + experience scores) for a
 * persona from project context. Caller persists via journeys.create.
 */
export const generateJourneyMap = action({
  args: {
    projectId: v.id("projects"),
    persona: v.optional(
      v.object({
        name: v.string(),
        role: v.optional(v.string()),
        goals: v.optional(v.array(v.string())),
        pains: v.optional(v.array(v.string())),
        objections: v.optional(v.array(v.string())),
        channels: v.optional(v.array(v.string())),
      }),
    ),
    scenario: v.optional(v.string()),
    stageCount: v.optional(v.number()),
  },
  handler: async (ctx, { projectId, persona, scenario, stageCount }) => {
    const userId = await requireActionUser(ctx);
    const project = await actionProjectSnapshot(ctx, userId, projectId);
    await consumeAiQuotaForAction(ctx, userId);
    const personaDesc = persona
      ? [
          `Persona name: ${persona.name}`,
          persona.role ? `Role/context: ${persona.role}` : "",
          persona.goals?.length ? `Goals: ${persona.goals.join("; ")}` : "",
          persona.pains?.length ? `Pains: ${persona.pains.join("; ")}` : "",
          persona.objections?.length
            ? `Objections: ${persona.objections.join("; ")}`
            : "",
          persona.channels?.length
            ? `Channels: ${persona.channels.join(", ")}`
            : "",
        ]
          .filter(Boolean)
          .join("\n")
      : "(no specific persona — use the primary buyer)";

    const lanesHint =
      "lanes are: Actions, Thoughts, Feelings, Pain points, Opportunities";

    const text = await complete(ctx, userId, projectId, "journeys.map_generation",
      `You are a CX strategist building a user journey map. Create a journey with ${stageCount ?? 5} stages (e.g. Trigger, Awareness, Consideration, Decision, Post-purchase — adapt to the scenario). For each stage fill all lanes (${lanesHint}) with 1-2 short, concrete, specific items — first-person voice for Actions/Thoughts/Feelings. Also give each stage an experience score 1-10 (10 = delightful). Return ONLY valid JSON shaped as:
{"name": string, "goal": string, "stages": [{"stage": string, "actions": string, "thoughts": string, "feelings": string, "pains": string, "opportunities": string, "score": number}]}`,
      [
        {
          role: "user",
          content: `${contextLines(project).join("\n")}\n\nPersona:\n${personaDesc}${scenario ? `\nScenario / goal of the journey: ${scenario}` : ""}`,
        },
      ],
      { temperature: 0.7, maxTokens: 1200, validateOutput: validateJourneyMapOutput },
    );

    const cleaned = text.replace(/```json|```/g, "").trim();
    const start = cleaned.indexOf("{");
    const end = cleaned.lastIndexOf("}");
    if (start === -1 || end === -1)
      throw new Error("AI returned an unreadable response");
    const raw = JSON.parse(cleaned.slice(start, end + 1)) as {
      name?: string;
      goal?: string;
      stages?: Array<Record<string, unknown>>;
    };

    const laneKeys = [
      "actions",
      "thoughts",
      "feelings",
      "pains",
      "opportunities",
    ] as const;
    const stages = (raw.stages ?? [])
      .filter((s) => typeof s.stage === "string" && s.stage.trim() !== "")
      .slice(0, 8)
      .map((s) => ({
        stage: (s.stage as string).trim(),
        cells: laneKeys.map((k) => {
          const v = s[k];
          return typeof v === "string" ? v.trim() : "";
        }),
        score:
          typeof s.score === "number"
            ? Math.max(0, Math.min(10, Math.round(s.score)))
            : undefined,
      }));
    if (!stages.length) throw new Error("AI returned no journey stages");

    return {
      name: raw.name?.trim() || "Customer journey",
      goal: raw.goal?.trim() || undefined,
      stages,
    };
  },
});

/**
 * Map a buying journey for a persona: stages with the buyer's core question
 * at each stage, and how the business should answer it. Persona + project
 * snapshots come from the client; caller persists via personas.update.
 */
export const generateJourney = action({
  args: {
    projectId: v.id("projects"),
    persona: v.object({
      name: v.string(),
      role: v.optional(v.string()),
      goals: v.optional(v.array(v.string())),
      pains: v.optional(v.array(v.string())),
      objections: v.optional(v.array(v.string())),
      channels: v.optional(v.array(v.string())),
      evidence: v.optional(v.string()),
    }),
  },
  handler: async (ctx, { projectId, persona }) => {
    const userId = await requireActionUser(ctx);
    const project = await actionProjectSnapshot(ctx, userId, projectId);
    await consumeAiQuotaForAction(ctx, userId);
    const personaDesc = [
      `Persona name: ${persona.name}`,
      persona.role ? `Role/context: ${persona.role}` : "",
      persona.goals?.length ? `Goals: ${persona.goals.join("; ")}` : "",
      persona.pains?.length ? `Pains: ${persona.pains.join("; ")}` : "",
      persona.objections?.length ? `Objections: ${persona.objections.join("; ")}` : "",
      persona.channels?.length ? `Channels: ${persona.channels.join(", ")}` : "",
    ]
      .filter(Boolean)
      .join("\n");

    const text = await complete(ctx, userId, projectId, "journeys.single_generation",
      `You are a senior marketing strategist. Map the buying journey for this persona against this business. Use 4-5 real journey stages (e.g. trigger/awareness, consideration, evaluation, decision, post-purchase — adapt to the persona). For each stage: the stage name, the question the buyer is really asking at that moment, and a concrete answer/action the business should give (touchpoint, content, proof). Return ONLY valid JSON (no markdown) shaped as:
{"stages": [{"stage": string, "question": string, "answer": string}]}`,
      [
        {
          role: "user",
          content: `${contextLines(project).join("\n")}\n\nPersona:\n${personaDesc}`,
        },
      ],
      { temperature: 0.6, maxTokens: 800, validateOutput: (output) => {
        const value = parseStructuredObject(output);
        if (!Array.isArray(value.stages) || !value.stages.length || value.stages.some((stage) => !stage || typeof stage !== "object" || typeof (stage as { stage?: unknown }).stage !== "string" || typeof (stage as { question?: unknown }).question !== "string")) throw new Error("invalid journey");
      } },
    );

    const cleaned = text.replace(/```json|```/g, "").trim();
    const start = cleaned.indexOf("{");
    const end = cleaned.lastIndexOf("}");
    if (start === -1 || end === -1) throw new Error("AI returned an unreadable response");
    const raw = JSON.parse(cleaned.slice(start, end + 1)) as {
      stages?: Array<{ stage?: string; question?: string; answer?: string }>;
    };
    const stages = (raw.stages ?? [])
      .filter(
        (s): s is { stage: string; question: string; answer: string } =>
          typeof s.stage === "string" &&
          s.stage.trim() !== "" &&
          typeof s.question === "string",
      )
      .slice(0, 6)
      .map((s) => ({
        stage: s.stage.trim(),
        question: s.question.trim(),
        answer: typeof s.answer === "string" ? s.answer.trim() : undefined,
      }));
    if (!stages.length) throw new Error("AI returned no journey stages");
    return { stages };
  },
});

/**
 * Define a marketing communication with AI: core message, rationale,
 * channels and audience. Returns parsed fields; caller persists via
 * communications.create. `influence` describes downstream modules the user
 * wants this comms work to potentially feed.
 */
export const generateComms = action({
  args: {
    projectId: v.id("projects"),
    personaLines: v.optional(v.array(v.string())),
    topic: v.string(),
    influence: v.optional(v.array(v.string())),
  },
  handler: async (ctx, { projectId, personaLines, topic, influence }) => {
    const userId = await requireActionUser(ctx);
    const project = await actionProjectSnapshot(ctx, userId, projectId);
    await consumeAiQuotaForAction(ctx, userId);
    const text = await complete(ctx, userId, projectId, "create.communication_generation",
      `You are a marketing communications director. Define ONE core marketing communication for the given topic: a crisp message (1-2 sentences a real customer would recognize themselves in), the strategic rationale, the best 2-4 channels, and the target audience. Return ONLY valid JSON (no markdown) shaped as:
{"name": string, "message": string, "rationale": string, "channels": string[], "audience": string}`,
      [
        {
          role: "user",
          content: `${contextLines(project).join("\n")}\n\nKnown personas:\n${(personaLines ?? []).join("\n") || "(none yet)"}\n\nTopic / direction: ${topic}\n${influence?.length ? `The user wants this to potentially influence these downstream areas: ${influence.join(", ")}. Mention that linkage in the rationale where natural.` : ""}`,
        },
      ],
      { temperature: 0.7, maxTokens: 600, validateOutput: (output) => {
        const value = parseStructuredObject(output);
        if (typeof value.name !== "string" || typeof value.message !== "string") throw new Error("invalid communication");
      } },
    );

    const cleaned = text.replace(/```json|```/g, "").trim();
    const start = cleaned.indexOf("{");
    const end = cleaned.lastIndexOf("}");
    if (start === -1 || end === -1) throw new Error("AI returned an unreadable response");
    const raw = JSON.parse(cleaned.slice(start, end + 1)) as {
      name?: string;
      message?: string;
      rationale?: string;
      channels?: unknown;
      audience?: string;
    };
    const channels = Array.isArray(raw.channels)
      ? raw.channels.filter((c): c is string => typeof c === "string").slice(0, 4)
      : [];

    return {
      name: raw.name?.trim() || topic,
      message: raw.message?.trim() || "",
      rationale: raw.rationale?.trim() || undefined,
      channels: channels.length ? channels : undefined,
      audience: raw.audience?.trim() || undefined,
    };
  },
});
