"use node";

import { v } from "convex/values";
import { action } from "./_generated/server";
import { vly } from "../lib/vly-integrations";

/* ── Shared helpers ───────────────────────────────────────────────────── */

async function complete(
  system: string,
  messages: Array<{ role: "user" | "assistant"; content: string }>,
  opts: { temperature?: number; maxTokens?: number } = {},
): Promise<string> {
  const res = await vly.ai.completion({
    model: "gpt-4o-mini",
    messages: [{ role: "system" as const, content: system }, ...messages],
    temperature: opts.temperature ?? 0.7,
    maxTokens: opts.maxTokens ?? 900,
  });
  if (!res.success || !res.data) {
    throw new Error(res.error ?? "AI request failed");
  }
  return res.data.choices[0]?.message?.content?.trim() ?? "";
}

/** Serializable project snapshot the client passes in (already fetched via
 *  projects.get + files.list) so these node actions stay db-free. */
export type ProjectSnapshot = {
  name: string;
  industry?: string;
  description?: string;
  websiteUrl?: string;
  productsServices?: string[];
  goals?: string[];
  competitors?: string[];
  gmbTitle?: string;
  gmbCategory?: string;
  gmbRating?: number;
  gmbReviews?: number;
  fileExcerpts?: string[];
};

export const projectSnapshotValidator = v.object({
  name: v.string(),
  industry: v.optional(v.string()),
  description: v.optional(v.string()),
  websiteUrl: v.optional(v.string()),
  productsServices: v.optional(v.array(v.string())),
  goals: v.optional(v.array(v.string())),
  competitors: v.optional(v.array(v.string())),
  gmbTitle: v.optional(v.string()),
  gmbCategory: v.optional(v.string()),
  gmbRating: v.optional(v.number()),
  gmbReviews: v.optional(v.number()),
  fileExcerpts: v.optional(v.array(v.string())),
});

function contextLines(p: ProjectSnapshot): string[] {
  return [
    `Project: ${p.name}`,
    p.industry ? `Industry: ${p.industry}` : "",
    p.description ? `Description: ${p.description}` : "",
    p.websiteUrl ? `Website: ${p.websiteUrl}` : "",
    p.productsServices?.length
      ? `Products/services: ${p.productsServices.join(", ")}`
      : "",
    p.goals?.length ? `Marketing goals: ${p.goals.join(", ")}` : "",
    p.competitors?.length ? `Competitors: ${p.competitors.join(", ")}` : "",
    p.gmbTitle
      ? `Google Business: ${p.gmbTitle}${p.gmbCategory ? ` (${p.gmbCategory})` : ""}${p.gmbRating ? ` — ${p.gmbRating}★ from ${p.gmbReviews ?? "?"} reviews` : ""}`
      : "",
    p.fileExcerpts?.length
      ? `Attached files (excerpts):\n${p.fileExcerpts.join("\n")}`
      : "",
  ].filter(Boolean);
}

const PERSONA_JSON_SHAPE = `Return ONLY valid JSON (no markdown fences) shaped as:
{
  "name": string,
  "role": string,
  "goals": string[],
  "pains": string[],
  "objections": string[],
  "channels": string[],
  "evidence": string
}`;

function parsePersona(json: string) {
  const cleaned = json.replace(/```json|```/g, "").trim();
  const start = cleaned.indexOf("{");
  const end = cleaned.lastIndexOf("}");
  if (start === -1 || end === -1) throw new Error("AI returned unparseable persona");
  const raw = JSON.parse(cleaned.slice(start, end + 1)) as {
    name?: string;
    role?: string;
    goals?: unknown;
    pains?: unknown;
    objections?: unknown;
    channels?: unknown;
    evidence?: string;
  };
  const arr = (x: unknown): string[] =>
    Array.isArray(x) ? x.filter((i): i is string => typeof i === "string").slice(0, 8) : [];
  return {
    name: raw.name?.trim() || "Persona",
    role: raw.role?.trim() || undefined,
    goals: arr(raw.goals),
    pains: arr(raw.pains),
    objections: arr(raw.objections),
    channels: arr(raw.channels),
    evidence: raw.evidence?.trim() || "Generated by AI from project context",
  };
}

/* ── Actions ──────────────────────────────────────────────────────────── */

/**
 * Generate a full persona from project details (files included) using AI.
 * The client passes a project snapshot (already fetched via projects.get);
 * the returned persona is persisted by the caller via personas.create.
 */
export const generatePersona = action({
  args: { project: projectSnapshotValidator, hint: v.optional(v.string()) },
  handler: async (_ctx, { project, hint }) => {
    const text = await complete(
      `You are a senior marketing strategist. Given the business context below, invent ONE realistic, specific buyer persona. Be concrete (names, habits, real-world details) and ground every trait in the business context. ${PERSONA_JSON_SHAPE}`,
      [
        {
          role: "user",
          content: `${contextLines(project).join("\n")}\n${hint ? `Extra guidance from the user: ${hint}` : ""}`,
        },
      ],
      { temperature: 0.8, maxTokens: 700 },
    );

    return parsePersona(text);
  },
});

/**
 * Chat with a persona (mode=persona — you talk to the buyer) or with an AI
 * marketing analyst about the persona (mode=analyst). Pure AI call — the
 * client passes the persona snapshot and prior thread, and persists the
 * exchange via personaChat.append.
 */
export const personaChat = action({
  args: {
    mode: v.union(v.literal("persona"), v.literal("analyst")),
    project: projectSnapshotValidator,
    persona: v.object({
      name: v.string(),
      role: v.optional(v.string()),
      goals: v.optional(v.array(v.string())),
      pains: v.optional(v.array(v.string())),
      objections: v.optional(v.array(v.string())),
      channels: v.optional(v.array(v.string())),
      evidence: v.optional(v.string()),
    }),
    history: v.optional(
      v.array(
        v.object({
          role: v.union(v.literal("user"), v.literal("assistant")),
          content: v.string(),
        }),
      ),
    ),
    message: v.string(),
  },
  handler: async (_ctx, { mode, project, persona, history, message }) => {
    const personaDesc = [
      `Persona name: ${persona.name}`,
      persona.role ? `Role/context: ${persona.role}` : "",
      persona.goals?.length ? `Goals: ${persona.goals.join("; ")}` : "",
      persona.pains?.length ? `Pains: ${persona.pains.join("; ")}` : "",
      persona.objections?.length ? `Objections: ${persona.objections.join("; ")}` : "",
      persona.channels?.length ? `Channels: ${persona.channels.join(", ")}` : "",
      persona.evidence ? `Evidence: ${persona.evidence}` : "",
    ]
      .filter(Boolean)
      .join("\n");

    const ctxBlock = contextLines(project).join("\n");

    const system =
      mode === "persona"
        ? `You ARE this buyer persona. Stay in character in every answer — first person, with their vocabulary, priorities and attitude. You know nothing about marketing theory; you are a real person. If asked about products/services, react as this person realistically would based on your pains and goals.\n\nBusiness selling to you:\n${ctxBlock}\n\nYour persona definition:\n${personaDesc}`
        : `You are an experienced marketing analyst. The user will ask about the persona below and how it relates to the business's marketing (content, website, campaigns, data). Answer with sharp, specific, actionable analysis. Reference the persona's pains/goals and the business context. Use short paragraphs or bullet lists.\n\nBusiness context:\n${ctxBlock}\n\nPersona:\n${personaDesc}`;

    const reply = await complete(
      system,
      [...(history ?? []).slice(-16), { role: "user" as const, content: message }],
      { temperature: mode === "persona" ? 0.9 : 0.5, maxTokens: 700 },
    );

    return reply;
  },
});

/**
 * Generate a full journey map (stages × lanes + experience scores) for a
 * persona from project context. Caller persists via journeys.create.
 */
export const generateJourneyMap = action({
  args: {
    project: projectSnapshotValidator,
    persona: v.optional(
      v.object({
        name: v.string(),
        role: v.optional(v.string()),
        goals: v.optional(v.array(v.string())),
        pains: v.optional(v.array(v.string())),
        objections: v.optional(v.array(v.string())),
        channels: v.optional(v.array(v.string())),
      }),
    ),
    scenario: v.optional(v.string()),
    stageCount: v.optional(v.number()),
  },
  handler: async (_ctx, { project, persona, scenario, stageCount }) => {
    const personaDesc = persona
      ? [
          `Persona name: ${persona.name}`,
          persona.role ? `Role/context: ${persona.role}` : "",
          persona.goals?.length ? `Goals: ${persona.goals.join("; ")}` : "",
          persona.pains?.length ? `Pains: ${persona.pains.join("; ")}` : "",
          persona.objections?.length
            ? `Objections: ${persona.objections.join("; ")}`
            : "",
          persona.channels?.length
            ? `Channels: ${persona.channels.join(", ")}`
            : "",
        ]
          .filter(Boolean)
          .join("\n")
      : "(no specific persona — use the primary buyer)";

    const lanesHint =
      "lanes are: Actions, Thoughts, Feelings, Pain points, Opportunities";

    const text = await complete(
      `You are a CX strategist building a user journey map. Create a journey with ${stageCount ?? 5} stages (e.g. Trigger, Awareness, Consideration, Decision, Post-purchase — adapt to the scenario). For each stage fill all lanes (${lanesHint}) with 1-2 short, concrete, specific items — first-person voice for Actions/Thoughts/Feelings. Also give each stage an experience score 1-10 (10 = delightful). Return ONLY valid JSON shaped as:
{"name": string, "goal": string, "stages": [{"stage": string, "actions": string, "thoughts": string, "feelings": string, "pains": string, "opportunities": string, "score": number}]}`,
      [
        {
          role: "user",
          content: `${contextLines(project).join("\n")}\n\nPersona:\n${personaDesc}${scenario ? `\nScenario / goal of the journey: ${scenario}` : ""}`,
        },
      ],
      { temperature: 0.7, maxTokens: 1200 },
    );

    const cleaned = text.replace(/```json|```/g, "").trim();
    const start = cleaned.indexOf("{");
    const end = cleaned.lastIndexOf("}");
    if (start === -1 || end === -1)
      throw new Error("AI returned an unreadable response");
    const raw = JSON.parse(cleaned.slice(start, end + 1)) as {
      name?: string;
      goal?: string;
      stages?: Array<Record<string, unknown>>;
    };

    const laneKeys = [
      "actions",
      "thoughts",
      "feelings",
      "pains",
      "opportunities",
    ] as const;
    const stages = (raw.stages ?? [])
      .filter((s) => typeof s.stage === "string" && s.stage.trim() !== "")
      .slice(0, 8)
      .map((s) => ({
        stage: (s.stage as string).trim(),
        cells: laneKeys.map((k) => {
          const v = s[k];
          return typeof v === "string" ? v.trim() : "";
        }),
        score:
          typeof s.score === "number"
            ? Math.max(0, Math.min(10, Math.round(s.score)))
            : undefined,
      }));
    if (!stages.length) throw new Error("AI returned no journey stages");

    return {
      name: raw.name?.trim() || "Customer journey",
      goal: raw.goal?.trim() || undefined,
      stages,
    };
  },
});

/**
 * Map a buying journey for a persona: stages with the buyer's core question
 * at each stage, and how the business should answer it. Persona + project
 * snapshots come from the client; caller persists via personas.update.
 */
export const generateJourney = action({
  args: {
    project: projectSnapshotValidator,
    persona: v.object({
      name: v.string(),
      role: v.optional(v.string()),
      goals: v.optional(v.array(v.string())),
      pains: v.optional(v.array(v.string())),
      objections: v.optional(v.array(v.string())),
      channels: v.optional(v.array(v.string())),
      evidence: v.optional(v.string()),
    }),
  },
  handler: async (_ctx, { project, persona }) => {
    const personaDesc = [
      `Persona name: ${persona.name}`,
      persona.role ? `Role/context: ${persona.role}` : "",
      persona.goals?.length ? `Goals: ${persona.goals.join("; ")}` : "",
      persona.pains?.length ? `Pains: ${persona.pains.join("; ")}` : "",
      persona.objections?.length ? `Objections: ${persona.objections.join("; ")}` : "",
      persona.channels?.length ? `Channels: ${persona.channels.join(", ")}` : "",
    ]
      .filter(Boolean)
      .join("\n");

    const text = await complete(
      `You are a senior marketing strategist. Map the buying journey for this persona against this business. Use 4-5 real journey stages (e.g. trigger/awareness, consideration, evaluation, decision, post-purchase — adapt to the persona). For each stage: the stage name, the question the buyer is really asking at that moment, and a concrete answer/action the business should give (touchpoint, content, proof). Return ONLY valid JSON (no markdown) shaped as:
{"stages": [{"stage": string, "question": string, "answer": string}]}`,
      [
        {
          role: "user",
          content: `${contextLines(project).join("\n")}\n\nPersona:\n${personaDesc}`,
        },
      ],
      { temperature: 0.6, maxTokens: 800 },
    );

    const cleaned = text.replace(/```json|```/g, "").trim();
    const start = cleaned.indexOf("{");
    const end = cleaned.lastIndexOf("}");
    if (start === -1 || end === -1) throw new Error("AI returned an unreadable response");
    const raw = JSON.parse(cleaned.slice(start, end + 1)) as {
      stages?: Array<{ stage?: string; question?: string; answer?: string }>;
    };
    const stages = (raw.stages ?? [])
      .filter(
        (s): s is { stage: string; question: string; answer: string } =>
          typeof s.stage === "string" &&
          s.stage.trim() !== "" &&
          typeof s.question === "string",
      )
      .slice(0, 6)
      .map((s) => ({
        stage: s.stage.trim(),
        question: s.question.trim(),
        answer: typeof s.answer === "string" ? s.answer.trim() : undefined,
      }));
    if (!stages.length) throw new Error("AI returned no journey stages");
    return { stages };
  },
});

/**
 * Define a marketing communication with AI: core message, rationale,
 * channels and audience. Returns parsed fields; caller persists via
 * communications.create. `influence` describes downstream modules the user
 * wants this comms work to potentially feed.
 */
export const generateComms = action({
  args: {
    project: projectSnapshotValidator,
    personaLines: v.optional(v.array(v.string())),
    topic: v.string(),
    influence: v.optional(v.array(v.string())),
  },
  handler: async (_ctx, { project, personaLines, topic, influence }) => {
    const text = await complete(
      `You are a marketing communications director. Define ONE core marketing communication for the given topic: a crisp message (1-2 sentences a real customer would recognize themselves in), the strategic rationale, the best 2-4 channels, and the target audience. Return ONLY valid JSON (no markdown) shaped as:
{"name": string, "message": string, "rationale": string, "channels": string[], "audience": string}`,
      [
        {
          role: "user",
          content: `${contextLines(project).join("\n")}\n\nKnown personas:\n${(personaLines ?? []).join("\n") || "(none yet)"}\n\nTopic / direction: ${topic}\n${influence?.length ? `The user wants this to potentially influence these downstream areas: ${influence.join(", ")}. Mention that linkage in the rationale where natural.` : ""}`,
        },
      ],
      { temperature: 0.7, maxTokens: 600 },
    );

    const cleaned = text.replace(/```json|```/g, "").trim();
    const start = cleaned.indexOf("{");
    const end = cleaned.lastIndexOf("}");
    if (start === -1 || end === -1) throw new Error("AI returned an unreadable response");
    const raw = JSON.parse(cleaned.slice(start, end + 1)) as {
      name?: string;
      message?: string;
      rationale?: string;
      channels?: unknown;
      audience?: string;
    };
    const channels = Array.isArray(raw.channels)
      ? raw.channels.filter((c): c is string => typeof c === "string").slice(0, 4)
      : [];

    return {
      name: raw.name?.trim() || topic,
      message: raw.message?.trim() || "",
      rationale: raw.rationale?.trim() || undefined,
      channels: channels.length ? channels : undefined,
      audience: raw.audience?.trim() || undefined,
    };
  },
});
